name: Automated Git Pull and Conditional Docker Compose Restart on GCP Instance

on:
  push:
    branches:
      - develop
      
env:
  USER_NAME: ${{ vars.USERNAME }}

jobs:
  access-gcp-instance:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: programmers-410523
        export_default_credentials: true

    - name: Access Compute Engine and Execute Command
      run: |
        gcloud compute ssh kylj0107@project-machine --zone=us-west4-b --command="\
          sudo su - airflow -c '\
            git diff --name-only HEAD@{1} HEAD | grep 'docker-compose.yml' && \
            IS_DOCKER_COMPOSE_CHANGED=$? && \
            if [ $IS_DOCKER_COMPOSE_CHANGED -eq 0 ]; then \
              echo \"docker-compose.yml changed, restarting Docker Compose\" && \
              docker-compose down && \
              docker-compose up -d && \
              echo \"Docker Compose restarted\" \
            else \
              echo \"No changes in docker-compose.yml\" \
            fi\
          '"
        echo "Docker Compose check and restart process completed"
      env:
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
            
