name: Automated Git Pull and Conditional Docker Compose Restart on GCP Instance
on:
  push:
    branches:
      - develop
      

jobs:
  access-gcp-instance:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: programmers-410523

    - name: Access Compute Engine and Execute Command
      env:
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      run: gcloud compute ssh kylj0107@project-machine --zone=us-west4-b --command="sudo su - airflow -c 'bash ~/dev-course-project-03/script.sh'"
