name: Automated Git Pull and Conditional Docker Compose Restart on GCP Instance
on:
  push:
    branches:
      - feature/workflows
      
env:
  USER_NAME: ${{ vars.USERNAME }}
jobs:
  access-gcp-instance:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: programmers-410523 # YOUR_GCP_PROJECT_ID
        export_default_credentials: true
    - name: Access Compute Engine and Execute Command
      run: |
        # SSH 접속 및 명령 실행
        gcloud compute ssh kylj0107@project-machine --zone=us-west4-b --command="\
          sudo su - airflow -c '\
            cd ~/dev-course-project-03 && \
            git config credential.helper \"cache --timeout=5\" && \
            echo username=$USER_NAME && echo password=$MY_GITHUB_TOKEN | git credential approve && \
            if git diff HEAD..origin/feature/workflows --name-only | grep -q 'docker-compose.yaml'; then \
              docker-compose down && \
              docker-compose up -d; \
            fi && \
            git pull \
          '"
      env:
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
